### PR TITLE
Remove dotenv from `package.json` and `README.md`

### PR DESCRIPTION
**Pull request by bickelj**
The `README.md` continues the pattern of using `.env` files, though this is one way of managing environment variables among many.

Issue #640

### CODE REVIEW

**Review by reefdog — CHANGES_REQUESTED** [review]
Good catch on the npm scripts!

And you're right that we need to add more guidance to the README; however, I don't think we should add these specific `source` prefixing to each command example. Different devs will tackle this in different ways, e.g., using direnv to auto-load env vars. This falls into the subjective dev category of which Node version manager to use.

Instead, we need to expand the [Setup](https://github.com/PhilanthropyDataCommons/service#setup) section with a note about each dev needing to make sure they're sourced using whatever method they want, with a few options (direnv; manual `set -a; source .env` before each `npm run` command; etc.)

**Comment by bickelj** [comment]
> And you're right that we need to add more guidance to the README; however, I don't think we should add these specific `source` prefixing to each command example. Different devs will tackle this in different ways, e.g., using direnv to auto-load env vars. This falls into the subjective dev category of which Node version manager to use.
> 
> Instead, we need to expand the [Setup](https://github.com/PhilanthropyDataCommons/service#setup) section with a note about each dev needing to make sure they're sourced using whatever method they want, with a few options (direnv; manual `set -a; source .env` before each `npm run` command; etc.)

Yes, fair enough.

I don't know anything about `direnv` so I couldn't speak to that in the README. But I agree that it's simpler to make a note to "make sure to set environment variables" and then de-clutter the rest. I have pushed a change to this effect.

**Review by reefdog — APPROVED** [review]
LGTM!

I wouldn't be opposed to actually pointing people to the [direnv](https://github.com/direnv/direnv) project as an example of what [some of us] use, or otherwise provide another recommendation so people don't have to run `set`/`source` before every dev session. But it looks like we've avoided pointing people to any such tooling thus far (like under the [Node version](https://github.com/PhilanthropyDataCommons/service#node-version) section), so this is consistent with history.

Thanks @bickelj!

**Review by slifty — APPROVED** [review]
Thank you for catching this and improving the documentation!

**Comment by slifty** [comment]
I don't remember what @bickelj's preference is but given that this is patching a breaking change I'm going to merge it since it's urgent.

**Pull request merged**
