### PR TITLE
Add tests for GET /opportunities

### PR DESCRIPTION
**Pull request by bickelj**
Issue #31 Implement GET /opportunities endpoint

### CODE REVIEW

**Review by slifty — APPROVED** [review]

**Comment by bickelj** [comment]
Wait. Why doesn't this change coverage?

**Comment by bickelj** [comment]
Duplicate tests. Removing.

**Review by slifty — CHANGES_REQUESTED** [review]
(I had approved not realizing these were dupe tests -- changing the review just to prevent accidental merge from seeing `approved`)

**Comment by bickelj** [comment]
Or not, I am taking a closer look.

**Comment by bickelj** [comment]
This turned out to be unneeded. In PR #70 I needed to remove duplicated code instead of creating a new PR.

**Pull request closed without merging**
