### PR TITLE
Use provenance in gold data retrieval

### PR DESCRIPTION
**Pull request by bickelj**
Prior to this commit, the organization aka change maker data retrieved were merely sorted by the datetime of insert into the PDC database. Now that provenance is potentially available via the `Sources` table, this commit creates a priority order for field values based on source:
1. organization sourced,
2. funder sourced,
3. data platform provider sourced,
4. old data marked as `pdc`-sourced (no provenance available).

After sorting fields by these classes of data sources, then within these classes the data are sorted by the datetime of insert. Finally, as before, a winner is chosen: the first value from the sorted data.

Suppose multiple funders posted values for an organization's "city", a data platform provider posted a value, and there are three old values left over from the era of pre-provenance data. In this case, the order of rows will have the multiple funders by datetime of insert followed by the data platform provider value followed by the old pre-provenance values by datetime of insert. The first value will win: the latest value from the funders.

Issue #1201

### CODE REVIEW

**Review by slifty — CHANGES_REQUESTED** [review]
The query change looks good and makes sense -- my only request is that we add test(s) for this new behavior.

**Comment by bickelj** [comment]
@slifty I added one test. I presume I should add more, but how many more? Should it be exhaustive? I suppose not.

**Comment by slifty** [comment]
@bickelj one is inifintely better than none so good enough I think!

In the grand scheme we may want to come up with some kind of test fixture that takes a data state and an expected "gold" set, and uses some kind of utility to translate that input state into proper database state, runs the query, and compares it with the expectation.

That can be done as a separate issue IMHO.

**Review by slifty — APPROVED** [review]
Thank you for the test, looks good!

**Pull request merged**
