### PR TITLE
Add sample TypeScript types and schema generator

### PR DESCRIPTION
**Pull request by bickelj**
One can run the generator to produce a types.json:

    npm run generate-json-schema

Issue #17 Add a couple of data types/schemas

### CODE REVIEW

**Comment by bickelj** [comment]
The above types in 7c748e9 are exploratory and so is the JSON schema generator. It would be nice to integrate these with the swagger/OpenAPI definitions somehow. I don't know if we would want full types with all optional fields present or read-only types (with full data) and write types (with just enough to write a new record). There also might be a completely different way of going about it. This is an exploration of one avenue.

**Comment by slifty** [comment]
Oh this is interesting -- I haven't seen it before.

I see how this would be immediately useful for populating the openapi spec, and that's cool to think about having automatically-updating documentation, though I think as you start to explore there might be downsides to automating that since we might lose the ability to be explicit in our documentation since the types might not always be 1:1 to what our API spec is intended to use.

Are there other things you are thinking the json schema will be used for outside of that?

**Comment by bickelj** [comment]
@slifty, sure we can pause. I am not entirely stuck on the idea of generating one to the other, but it seems like we ought to if it can work. I am also OK with deferring the definition of data exchange schemas, deferring definition of TypeScript types, etc., to another time or also to another PR/issue.

**Comment by slifty** [comment]
Yeah that sounds good; we should be defining types as we implement endpoints anyway (that way we avoid the thrash of accidentally over-implementing against imaginary use cases)

**Comment by bickelj** [comment]
I think AJV promises much regarding JSON schema and can probably be integrated with the OpenAPI somehow. This experiment or proposal served its purpose.

**Pull request closed without merging**
