### PR TITLE
Deploy on DigitalOcean App Platform

### PR DESCRIPTION
**Pull request by jasonaowen**
> [DigitalOcean App Platform](https://docs.digitalocean.com/products/app-platform/) is a Platform-as-a-Service (PaaS) offering that allows developers to publish code directly to DigitalOcean servers without worrying about the underlying infrastructure.

The majority of the work in migrating is in configuring the application on the DigitalOcean side. To do so, some improved documentation and logging is helpful, as is capturing the configuration into an [app template](https://docs.digitalocean.com/products/app-platform/how-to/add-deploy-do-button/).

Issue https://github.com/PhilanthropyDataCommons/deploy/issues/118 Migrate to DigitalOcean Apps

### CODE REVIEW

**Comment by jasonaowen** [comment]
I've created a `pdc-service-test` app in our DigitalOcean account, and configured it in DNS with @jmergy, so that https://api-test.philanthropydatacommons.org/ is now running off the DO app. I believe both of you, @bickelj and @slifty, have permission to log in and examine it, if you like.

I migrated the database off the old api-test.pdco by dumping the database, adding the droplet to the allowed list of the managed database, and restoring into it:

```
docker exec -i deploy_database_1 \
  pg_dump \
    --user pdc \
    --clean \
    --no-owner \
    --verbose \
    --quote-all-identifiers pdc \
   | bzip2 --best \
  > pdc-testing.pg_dump.$(date -u -Is).sql.bz2
export PGPASSWORD=(managed instance password)
bzcat pdc-testing.pg_dump.${TIMESTAMP}.sql.bz2 \
  | psql \
    -U (managed instance username) \
    -h (managed instance hostname) \
    -p (managed instance port) \
    -d (manage instance databasename)
```

The api-test.pdco droplet is still running; you can find the IP address in the DO interface.

I tested the deploy button by creating a new branch [digitalocean-app-test](https://github.com/PhilanthropyDataCommons/service/tree/digitalocean-app-test) which changes the branch name in the link and in the template, and verified that (after following the database upgrade instructions in HOSTING.md) it results in a working API instance.

**Comment by jasonaowen** [comment]
Once this is merged, I intend to create a new instance by using the template, applying the environment variable values used in the api.pdco droplet, migrating the database in the same way, and updating DNS.

**Comment by slifty** [comment]
Please add tests for this documentation (this is a joke, please disregard)

**Comment by bickelj** [comment]
@jasonaowen What problem does this solve? I see an issue related but no description of the problem.

**Review by slifty — APPROVED** [review]
This all makes sense -- My only note is that I wasn't sure how the deploy.template.yaml was used from the code inspection / commit message itself, and had to go to the documentation linked.  It might be worth just having one line somewhere (in commit message) that underscores that asset is used BY digital ocean as part of launching an app.

Yes that's in the documentation linked, but that link might break over time and also it seems reasonable to have that nod in our code base directly.

**Comment by jasonaowen** [comment]
@slifty good call, I rebased and reworded! And thank you for updating the issue.

**Pull request merged**
