### PR TITLE
Add database support

### PR DESCRIPTION
**Pull request by bickelj**
This expands on https://github.com/PhilanthropyDataCommons/service/pull/12 from 61d3fb2

### CODE REVIEW

**Comment by bickelj** [comment]
Progress at https://github.com/PhilanthropyDataCommons/service/runs/7138069933?check_suite_focus=true#step:6:15
> error: password authentication failed for user "runner"

**Comment by bickelj** [comment]
So I rebased 8-add-database-support onto main at 848657b5e9fab70895f7a198cecea642aad8cc1a but I am not so confident in the rewrite. @slifty we could either merge this PR or you could re-re-base in PR #12 or whatever. I didn't want to try to push directly to your work-in-progress branch, but maybe that was also an option.

**Comment by slifty** [comment]
I cherry picked the commits here and squashed them into the originally broken commit, so I think we can close this once #12 is merged in.

**Comment by bickelj** [comment]
Resolved in original pull request #12

**Pull request closed without merging**
