### PR TITLE
Remove Docker build action

### PR DESCRIPTION
**Pull request by jasonaowen**
Now that we are using a different deployment system, we no longer need to build Docker images. Those were only ever for us - we don't know of any users who relied on the published images.

Save build time, storage space, and remove the time-bomb that is using a personal access token to notify another repository.

After this is merged, delete the `REPO_ACCESS_TOKEN` secret from this repository.

Issue PhilanthropyDataCommons/deploy#118 Migrate to DigitalOcean Apps
Issue #622 Change deploy model

### CODE REVIEW

**Comment by jasonaowen** [comment]
I do not touch the `Dockerfile` in this PR, as I recognize that some of you may be using it. If you are, speak up; if nobody is, maybe we should remove it, or at least move it into a `contrib` subdirectory to indicate that it should work but it's not being actively maintained?

**Comment by slifty** [comment]
@jasonaowen Just to be explicit: this PR is doing two things -- no longer triggering deploy from docker, but also no longer building the docker file.

I do agree that we don't need to support docker for development at this point, but I also wanted to just be explicit that this is doing more than just what is described in #118.

If we *were* to have a real docker-dev environment we would probably want to use docker compose and set up psql + keycloak containers as well.  I think that's a reasonable thing to do if it were a priority.  We may find that that becomes a valued product when we have a third party dev team coding against the API.

**Review by slifty — APPROVED** [review]
I think it's a reasonable choice to remove docker support right now, though I would not be surprised if we decide to revisit that decision in the coming months depending on third party dev feedback.

**Comment by jasonaowen** [comment]
That's a good callout, thank you, @slifty. I'll update the commit message and rebase, then merge after checks have passed.

**Pull request merged**
